//! The validation gate: every file against its schema, plus the invariants
//! no schema can express (cross-file version agreement, sources that exist,
//! reserved slugs, placeholders that are really placeholders).
//!
//! Findings are kept in three kinds because they mean different things: a
//! broken *schema* is a tooling problem, not a bad entry, and must never be
//! reported as one.

use std::collections::BTreeMap;
use std::path::Path;

use serde::Serialize;
use studio_core::config::Target;

use crate::generate::{CLAUDE_MANIFEST, CODEX_MANIFEST, CODEX_MCP_JSON, MCP_JSON, SERVER_YAML};
use crate::model::{Kind, Marketplace};
use crate::ojson::Json;
use crate::schema::{self, SchemaId};
use crate::tree::{self, ENTRY_ROOTS};
use crate::{CLAUDE_CATALOG, CODEX_CATALOG, SCHEMA_DIR, yaml};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum FindingKind {
    /// A schema itself is broken (in the repo's `schema/`).
    SchemaInvalid,
    /// A file does not match its schema (or does not parse).
    Schema,
    /// A cross-file rule is broken.
    Invariant,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Finding {
    pub kind: FindingKind,
    /// Repo-relative path the finding is about.
    pub file: String,
    pub message: String,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct ValidationReport {
    pub findings: Vec<Finding>,
    pub files_checked: usize,
    /// Informational: things worth knowing that are not failures.
    pub notes: Vec<String>,
}

impl ValidationReport {
    pub fn is_ok(&self) -> bool {
        self.findings.is_empty()
    }
    /// Problems with the schemas themselves.
    pub fn schema_errors(&self) -> impl Iterator<Item = &Finding> {
        self.findings
            .iter()
            .filter(|f| f.kind == FindingKind::SchemaInvalid)
    }
    /// Problems with the marketplace's data (schema violations + invariants).
    pub fn data_errors(&self) -> impl Iterator<Item = &Finding> {
        self.findings
            .iter()
            .filter(|f| f.kind != FindingKind::SchemaInvalid)
    }

    fn push(&mut self, kind: FindingKind, file: impl Into<String>, message: impl Into<String>) {
        self.findings.push(Finding {
            kind,
            file: file.into(),
            message: message.into(),
        });
    }
}

/// Validate a marketplace working tree.
pub fn validate_dir(root: &Path, m: &Marketplace) -> ValidationReport {
    let mut r = ValidationReport::default();
    if !root.is_dir() {
        r.push(
            FindingKind::Invariant,
            root.display().to_string(),
            "not a directory",
        );
        return r;
    }

    check_repo_schemas(root, &mut r);
    check_placeholder_config(m, &mut r);

    let claude = check_catalog(root, m, Target::Claude, &mut r);
    let codex = check_catalog(root, m, Target::Codex, &mut r);

    // Per-entry files against their schemas — managed or not.
    let mut schema_clean: BTreeMap<String, bool> = BTreeMap::new();
    for top in ENTRY_ROOTS {
        let Ok(rd) = std::fs::read_dir(root.join(top)) else {
            continue;
        };
        let mut dirs: Vec<_> = rd
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        for d in dirs {
            let rel = format!(
                "{top}/{}",
                d.file_name().unwrap_or_default().to_string_lossy()
            );
            let before = r.findings.len();
            check_entry_files(root, &rel, &mut r);
            schema_clean.insert(rel, r.findings.len() == before);
        }
    }

    let scan = tree::scan(root);
    for (file, problem) in &scan.broken {
        let rel = file
            .trim_end_matches(&format!("/{SERVER_YAML}"))
            .to_string();
        if schema_clean.get(&rel).copied().unwrap_or(true) {
            r.push(FindingKind::Schema, file.clone(), problem.clone());
        }
    }
    for u in &scan.unmanaged {
        r.notes.push(format!(
            "{u}: no server.yaml (hand-managed; not generated by Studio)"
        ));
    }

    // Invariants over loaded entries.
    let mut seen: BTreeMap<&str, &str> = BTreeMap::new();
    for p in &scan.plugins {
        let yaml_path = p.path(SERVER_YAML);
        let dir_name = p.rel_dir.rsplit('/').next().unwrap_or("");
        if p.slug != dir_name {
            r.push(
                FindingKind::Invariant,
                &yaml_path,
                format!(
                    "slug {:?} does not match its directory {dir_name:?}",
                    p.slug
                ),
            );
        }
        if m.is_reserved(&p.slug) {
            r.push(
                FindingKind::Invariant,
                &yaml_path,
                format!("slug {:?} is reserved", p.slug),
            );
        }
        if let Some(other) = seen.insert(&p.slug, &p.rel_dir) {
            r.push(
                FindingKind::Invariant,
                &yaml_path,
                format!("duplicate slug {:?} (also in {other})", p.slug),
            );
        }
        let e = &p.entry;
        for (field, v) in [
            ("url", e.url.as_deref()),
            ("homepage", e.homepage.as_deref()),
        ] {
            if let Some(v) = v
                && (!v.starts_with("https://") || v.chars().any(char::is_whitespace))
            {
                r.push(
                    FindingKind::Invariant,
                    &yaml_path,
                    format!("`{field}` must be https:// with no whitespace"),
                );
            }
        }
        if e.kind() == Kind::McpServer {
            if !root.join(p.path(MCP_JSON)).is_file() {
                r.push(
                    FindingKind::Invariant,
                    p.path(MCP_JSON),
                    "missing (mcp-server entries need it)",
                );
            }
            if m.has(Target::Codex)
                && e.auth_type().is_credentialed()
                && !root.join(p.path(CODEX_MCP_JSON)).is_file()
            {
                r.push(
                    FindingKind::Invariant,
                    p.path(CODEX_MCP_JSON),
                    "missing (credentialed entries need it: Codex reads http_headers)",
                );
            }
        }

        // Version agreement.
        let want = e.version();
        let mut got: Vec<(String, String)> = Vec::new();
        for (target, file) in [
            (Target::Claude, CLAUDE_MANIFEST),
            (Target::Codex, CODEX_MANIFEST),
        ] {
            if !m.has(target) {
                continue;
            }
            match tree::read_json(root, &p.path(file)) {
                Ok(Some(j)) => {
                    if let Some(v) = j.get("version").and_then(Json::as_str) {
                        got.push((p.path(file), v.to_string()));
                    }
                }
                Ok(None) => r.push(FindingKind::Invariant, p.path(file), "missing"),
                Err(_) => {} // reported by the schema pass
            }
        }
        if let Some(c) = &claude {
            match catalog_entry(c, &p.slug) {
                Some(ce) => {
                    if let Some(v) = ce.get("version").and_then(Json::as_str) {
                        got.push((CLAUDE_CATALOG.to_string(), v.to_string()));
                    }
                }
                None => r.push(
                    FindingKind::Invariant,
                    CLAUDE_CATALOG,
                    format!("{} is not listed", p.slug),
                ),
            }
        }
        if let Some(c) = &codex
            && catalog_entry(c, &p.slug).is_none()
        {
            r.push(
                FindingKind::Invariant,
                CODEX_CATALOG,
                format!("{} is not listed", p.slug),
            );
        }
        let wrong: Vec<String> = got
            .iter()
            .filter(|(_, v)| v != want)
            .map(|(f, v)| format!("{f} has {v}"))
            .collect();
        if !wrong.is_empty() {
            r.push(
                FindingKind::Invariant,
                &yaml_path,
                format!("version {want} disagrees: {}", wrong.join(", ")),
            );
        }
    }

    // Placeholders: any header value that isn't the placeholder may be a
    // real credential. Never echo the value.
    for top in ENTRY_ROOTS {
        for rel in tree::files_under(root, top) {
            let headers_key = if rel.ends_with(&format!("/{CODEX_MCP_JSON}")) {
                "http_headers"
            } else if rel.ends_with(&format!("/{MCP_JSON}")) {
                "headers"
            } else {
                continue;
            };
            check_placeholders(root, &rel, headers_key, m, &mut r);
        }
    }
    r
}

fn catalog_entry<'a>(catalog: &'a Json, name: &str) -> Option<&'a Json> {
    catalog
        .get("plugins")?
        .as_array()?
        .iter()
        .find(|p| p.get("name").and_then(Json::as_str) == Some(name))
}

fn check_repo_schemas(root: &Path, r: &mut ValidationReport) {
    let dir = root.join(SCHEMA_DIR);
    if !dir.is_dir() {
        r.notes.push(format!(
            "no {SCHEMA_DIR}/ directory: this marketplace predates the schemas (`adopt` adds them)"
        ));
        return;
    }
    for id in SchemaId::ALL {
        let rel = format!("{SCHEMA_DIR}/{}", id.file_name());
        match std::fs::read_to_string(root.join(&rel)) {
            Ok(text) => {
                r.files_checked += 1;
                if let Err(e) = schema::compile(&text) {
                    r.push(FindingKind::SchemaInvalid, rel, e);
                }
            }
            Err(_) => r
                .notes
                .push(format!("{rel} is missing (CI cannot check that file kind)")),
        }
    }
}

fn check_placeholder_config(m: &Marketplace, r: &mut ValidationReport) {
    let p = &m.placeholder;
    let looks_like_placeholder = p.len() >= 3
        && p.starts_with('<')
        && p.ends_with('>')
        && p[1..p.len() - 1]
            .chars()
            .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_' || c == '-');
    if !looks_like_placeholder {
        r.push(
            FindingKind::Invariant,
            "studio.toml",
            "credential_placeholder must look like <YOUR_API_KEY> (angle brackets, capitals), never a real value",
        );
    }
}

fn check_catalog(
    root: &Path,
    m: &Marketplace,
    target: Target,
    r: &mut ValidationReport,
) -> Option<Json> {
    let (rel, id) = match target {
        Target::Claude => (CLAUDE_CATALOG, SchemaId::ClaudeMarketplace),
        Target::Codex => (CODEX_CATALOG, SchemaId::CodexMarketplace),
    };
    let j = match tree::read_json(root, rel) {
        Ok(Some(j)) => j,
        Ok(None) => {
            if m.has(target) {
                r.push(FindingKind::Invariant, rel, "missing");
            }
            return None;
        }
        Err(e) => {
            r.push(FindingKind::Schema, rel, e);
            return None;
        }
    };
    r.files_checked += 1;
    for e in schema::check(id, &j.to_value()) {
        r.push(FindingKind::Schema, rel, e);
    }
    let mut names: BTreeMap<String, ()> = BTreeMap::new();
    for p in j
        .get("plugins")
        .and_then(Json::as_array)
        .into_iter()
        .flatten()
    {
        let name = p
            .get("name")
            .and_then(Json::as_str)
            .unwrap_or("?")
            .to_string();
        if names.insert(name.clone(), ()).is_some() {
            r.push(
                FindingKind::Invariant,
                rel,
                format!("{name} is listed twice"),
            );
        }
        if let Some(src) = p.get("source").and_then(Json::as_str) {
            if src.contains("..") {
                r.push(
                    FindingKind::Invariant,
                    rel,
                    format!("{name}: source {src:?} must not contain .."),
                );
            } else if !root.join(src).is_dir() {
                r.push(
                    FindingKind::Invariant,
                    rel,
                    format!("{name}: source {src} does not exist"),
                );
            }
        }
    }
    Some(j)
}

fn check_entry_files(root: &Path, rel_dir: &str, r: &mut ValidationReport) {
    let yaml_rel = format!("{rel_dir}/{SERVER_YAML}");
    if let Ok(text) = std::fs::read_to_string(root.join(&yaml_rel)) {
        r.files_checked += 1;
        match yaml::to_json(&text) {
            Ok(v) => {
                for e in schema::check(SchemaId::Server, &v) {
                    r.push(FindingKind::Schema, &yaml_rel, e);
                }
            }
            Err(e) => r.push(FindingKind::Schema, &yaml_rel, e.to_string()),
        }
    }
    for (file, id) in [
        (CLAUDE_MANIFEST, SchemaId::ClaudePlugin),
        (CODEX_MANIFEST, SchemaId::CodexPlugin),
        (MCP_JSON, SchemaId::McpJson),
        (CODEX_MCP_JSON, SchemaId::CodexMcpJson),
    ] {
        let rel = format!("{rel_dir}/{file}");
        match tree::read_json(root, &rel) {
            Ok(Some(j)) => {
                r.files_checked += 1;
                for e in schema::check(id, &j.to_value()) {
                    r.push(FindingKind::Schema, &rel, e);
                }
            }
            Ok(None) => {}
            Err(e) => r.push(FindingKind::Schema, &rel, e),
        }
    }
}

fn check_placeholders(
    root: &Path,
    rel: &str,
    headers_key: &str,
    m: &Marketplace,
    r: &mut ValidationReport,
) {
    let Ok(Some(j)) = tree::read_json(root, rel) else {
        return;
    };
    let allowed = [m.placeholder.clone(), format!("Bearer {}", m.placeholder)];
    let Some(Json::Object(servers)) = j.get("mcpServers") else {
        return;
    };
    for (name, server) in servers {
        let Some(Json::Object(headers)) = server.get(headers_key) else {
            continue;
        };
        for (h, v) in headers {
            let ok = v.as_str().is_some_and(|v| allowed.iter().any(|a| a == v));
            if !ok {
                r.push(
                    FindingKind::Invariant,
                    rel,
                    format!(
                        "{name}: header {h} is not the credential placeholder {} — it may be a real credential (value not shown)",
                        m.placeholder
                    ),
                );
            }
        }
    }
}

/// Validate a single file by kind (for templates, fixtures and tests).
pub fn validate_text(id: SchemaId, text: &str, is_yaml: bool) -> Result<Vec<String>, String> {
    let v = if is_yaml {
        yaml::to_json(text).map_err(|e| e.to_string())?
    } else {
        serde_json::from_str(text).map_err(|e| format!("not valid JSON: {e}"))?
    };
    Ok(schema::check(id, &v))
}
